/**
 * HouseDB API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface DomoticzP1Consumption {
    c1?: string;

    c2?: string;

    c3?: string;

    c4?: string;

    d?: string;

    r1?: string;

    r2?: string;

    v?: string;

    v2?: string;

    date?: Date;

    dayUsage?: number;

}
