// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Exporter.HouseDBService.Models
{
    using Exporter.HouseDBService;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class Device
    {
        /// <summary>
        /// Initializes a new instance of the Device class.
        /// </summary>
        public Device()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the Device class.
        /// </summary>
        public Device(string name = default(string), int? dataMineChannel = default(int?), int? veraChannel = default(int?), int? domoticzIdx = default(int?), bool? isForKwhImport = default(bool?), bool? isForTemperatureImport = default(bool?), long? id = default(long?), System.DateTime? dateDeleted = default(System.DateTime?), bool? isNew = default(bool?), bool? isDeleted = default(bool?))
        {
            Name = name;
            DataMineChannel = dataMineChannel;
            VeraChannel = veraChannel;
            DomoticzIdx = domoticzIdx;
            IsForKwhImport = isForKwhImport;
            IsForTemperatureImport = isForTemperatureImport;
            Id = id;
            DateDeleted = dateDeleted;
            IsNew = isNew;
            IsDeleted = isDeleted;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dataMineChannel")]
        public int? DataMineChannel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "veraChannel")]
        public int? VeraChannel { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "domoticzIdx")]
        public int? DomoticzIdx { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isForKwhImport")]
        public bool? IsForKwhImport { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isForTemperatureImport")]
        public bool? IsForTemperatureImport { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "id")]
        public long? Id { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateDeleted")]
        public System.DateTime? DateDeleted { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isNew")]
        public bool? IsNew { get; private set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "isDeleted")]
        public bool? IsDeleted { get; private set; }

    }
}
