// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Exporter.HouseDBService.Models
{
    using Exporter.HouseDBService;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DomoticzPostDatabaseFile
    {
        /// <summary>
        /// Initializes a new instance of the DomoticzPostDatabaseFile class.
        /// </summary>
        public DomoticzPostDatabaseFile()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DomoticzPostDatabaseFile class.
        /// </summary>
        public DomoticzPostDatabaseFile(byte[] byteArray = default(byte[]), System.DateTime? dateTime = default(System.DateTime?), string fileName = default(string))
        {
            ByteArray = byteArray;
            DateTime = dateTime;
            FileName = fileName;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "byteArray")]
        public byte[] ByteArray { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dateTime")]
        public System.DateTime? DateTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fileName")]
        public string FileName { get; set; }

    }
}
