// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Exporter.HouseDBService.Models
{
    using Exporter.HouseDBService;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class DomoticzKwhValue
    {
        /// <summary>
        /// Initializes a new instance of the DomoticzKwhValue class.
        /// </summary>
        public DomoticzKwhValue()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the DomoticzKwhValue class.
        /// </summary>
        public DomoticzKwhValue(double? c = default(double?), System.DateTime? d = default(System.DateTime?), double? v = default(double?))
        {
            C = c;
            D = d;
            V = v;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "c")]
        public double? C { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "d")]
        public System.DateTime? D { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "v")]
        public double? V { get; set; }

    }
}
