// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Exporter.HouseDBService.Models
{
    using Exporter.HouseDBService;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class DomoticzMotionDetectionClientModel
    {
        /// <summary>
        /// Initializes a new instance of the
        /// DomoticzMotionDetectionClientModel class.
        /// </summary>
        public DomoticzMotionDetectionClientModel()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the
        /// DomoticzMotionDetectionClientModel class.
        /// </summary>
        public DomoticzMotionDetectionClientModel(Device device = default(Device), IList<DomoticzMotionDetection> motionDetections = default(IList<DomoticzMotionDetection>))
        {
            Device = device;
            MotionDetections = motionDetections;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "device")]
        public Device Device { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "motionDetections")]
        public IList<DomoticzMotionDetection> MotionDetections { get; set; }

    }
}
