// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Exporter.HouseDBService.Models
{
    using Exporter.HouseDBService;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PostGetKwhYearUsage
    {
        /// <summary>
        /// Initializes a new instance of the PostGetKwhYearUsage class.
        /// </summary>
        public PostGetKwhYearUsage()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PostGetKwhYearUsage class.
        /// </summary>
        public PostGetKwhYearUsage(int? year = default(int?), int? deviceID = default(int?))
        {
            Year = year;
            DeviceID = deviceID;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "year")]
        public int? Year { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "deviceID")]
        public int? DeviceID { get; set; }

    }
}
