// Code generated by Microsoft (R) AutoRest Code Generator 1.2.2.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Exporter.HouseDBService.Models
{
    using Exporter.HouseDBService;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class RaspicamSettings
    {
        /// <summary>
        /// Initializes a new instance of the RaspicamSettings class.
        /// </summary>
        public RaspicamSettings()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the RaspicamSettings class.
        /// </summary>
        public RaspicamSettings(string host = default(string), int? port = default(int?), string path = default(string), string auth = default(string))
        {
            Host = host;
            Port = port;
            Path = path;
            Auth = auth;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "host")]
        public string Host { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "port")]
        public int? Port { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "path")]
        public string Path { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "auth")]
        public string Auth { get; set; }

    }
}
