/**
 * HouseDB API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { Http, Headers, URLSearchParams }                    from '@angular/http';
import { RequestMethod, RequestOptions, RequestOptionsArgs } from '@angular/http';
import { Response, ResponseContentType }                     from '@angular/http';

import { Observable }                                        from 'rxjs/Observable';
import 'rxjs/add/operator/map';

import * as models                                           from '../model/models';
import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class ExporterApi {

    protected basePath = 'https://localhost';
    public defaultHeaders: Headers = new Headers();
    public configuration: Configuration = new Configuration();

    constructor(protected http: Http, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
        }
    }

    /**
     * 
     * @param clientModel 
     */
    public exporterInsertDomoticzKwhValuesPost(clientModel?: models.DomoticzKwhValuesClientModel, extraHttpRequestParams?: any): Observable<{}> {
        return this.exporterInsertDomoticzKwhValuesPostWithHttpInfo(clientModel, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param domoticzP1Consumptions 
     */
    public exporterInsertDomoticzP1ConsumptionPost(domoticzP1Consumptions?: Array<models.DomoticzP1Consumption>, extraHttpRequestParams?: any): Observable<{}> {
        return this.exporterInsertDomoticzP1ConsumptionPostWithHttpInfo(domoticzP1Consumptions, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param clientModel 
     */
    public exporterInsertMotionDetectionValuesPost(clientModel?: models.DomoticzMotionDetectionClientModel, extraHttpRequestParams?: any): Observable<{}> {
        return this.exporterInsertMotionDetectionValuesPostWithHttpInfo(clientModel, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param clientModel 
     */
    public exporterInsertValuesForCachingPost(clientModel?: models.DomoticzValuesForCachingClientModel, extraHttpRequestParams?: any): Observable<{}> {
        return this.exporterInsertValuesForCachingPostWithHttpInfo(clientModel, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }

    /**
     * 
     * @param domoticzPostDatabaseFile 
     */
    public exporterUploadDatabasePost(domoticzPostDatabaseFile?: models.DomoticzPostDatabaseFile, extraHttpRequestParams?: any): Observable<{}> {
        return this.exporterUploadDatabasePostWithHttpInfo(domoticzPostDatabaseFile, extraHttpRequestParams)
            .map((response: Response) => {
                if (response.status === 204) {
                    return undefined;
                } else {
                    return response.json() || {};
                }
            });
    }


    /**
     * 
     * 
     * @param clientModel 
     */
    public exporterInsertDomoticzKwhValuesPostWithHttpInfo(clientModel?: models.DomoticzKwhValuesClientModel, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/Exporter/InsertDomoticzKwhValues';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: clientModel == null ? '' : JSON.stringify(clientModel), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param domoticzP1Consumptions 
     */
    public exporterInsertDomoticzP1ConsumptionPostWithHttpInfo(domoticzP1Consumptions?: Array<models.DomoticzP1Consumption>, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/Exporter/InsertDomoticzP1Consumption';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: domoticzP1Consumptions == null ? '' : JSON.stringify(domoticzP1Consumptions), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param clientModel 
     */
    public exporterInsertMotionDetectionValuesPostWithHttpInfo(clientModel?: models.DomoticzMotionDetectionClientModel, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/Exporter/InsertMotionDetectionValues';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: clientModel == null ? '' : JSON.stringify(clientModel), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param clientModel 
     */
    public exporterInsertValuesForCachingPostWithHttpInfo(clientModel?: models.DomoticzValuesForCachingClientModel, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/Exporter/InsertValuesForCaching';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: clientModel == null ? '' : JSON.stringify(clientModel), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

    /**
     * 
     * 
     * @param domoticzPostDatabaseFile 
     */
    public exporterUploadDatabasePostWithHttpInfo(domoticzPostDatabaseFile?: models.DomoticzPostDatabaseFile, extraHttpRequestParams?: any): Observable<Response> {
        const path = this.basePath + '/Exporter/UploadDatabase';

        let queryParameters = new URLSearchParams();
        let headers = new Headers(this.defaultHeaders.toJSON()); // https://github.com/angular/angular/issues/6845
        // to determine the Content-Type header
        let consumes: string[] = [
            'application/json',
            'text/json',
            'application/json-patch+json'
        ];

        // to determine the Accept header
        let produces: string[] = [
        ];

        headers.set('Content-Type', 'application/json');

        let requestOptions: RequestOptionsArgs = new RequestOptions({
            method: RequestMethod.Post,
            headers: headers,
            body: domoticzPostDatabaseFile == null ? '' : JSON.stringify(domoticzPostDatabaseFile), // https://github.com/angular/angular/issues/10612
            search: queryParameters,
            withCredentials:this.configuration.withCredentials
        });
        // https://github.com/swagger-api/swagger-codegen/issues/4037
        if (extraHttpRequestParams) {
            requestOptions = (<any>Object).assign(requestOptions, extraHttpRequestParams);
        }

        return this.http.request(path, requestOptions);
    }

}
